In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./stage_2_train_labels.csv")
data.head()

                              patientId      x      y  width  height  Target
0  0004cfab-14fd-4e49-80ba-63a80b6bddd6    NaN    NaN    NaN     NaN       0
1  00313ee0-9eaa-42f4-b0ab-c148ed3241cd    NaN    NaN    NaN     NaN       0
2  00322d4d-1c29-4943-afc9-b6754be640eb    NaN    NaN    NaN     NaN       0
3  003d8fa0-6bf1-40ed-b54c-ac657f8495c5    NaN    NaN    NaN     NaN       0
4  00436515-870c-4b36-a041-de91049b9ab4  264.0  152.0  213.0   379.0       1

In [3]:
data.shape

(30227, 6)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30227 entries, 0 to 30226
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   patientId  30227 non-null  object
 1   x          9555 non-null   float64
 2   y          9555 non-null   float64
 3   width      9555 non-null   float64
 4   height     9555 non-null   float64
 5   Target     30227 non-null  int64
dtypes: float64(4), int64(1), object(1)
memory usage: 1.4+ MB

In [5]:
(data["Target"] == 0).sum()

np.int64(20672)

In [6]:
(data["Target"] == 1).sum()

np.int64(9555)

There's a clear unbalance in the data, 9555 sample per class is fair enough for a finetuning task

In [7]:
N = 9555

balanced_df = pd.concat([
    data[data["Target"] == 1],
    data[data["Target"] == 0].sample(n=N, random_state=42)
], ignore_index=True)

balanced_df.head()

                              patientId      x      y  width  height  Target
0  00436515-870c-4b36-a041-de91049b9ab4  264.0  152.0  213.0   379.0       1
1  00436515-870c-4b36-a041-de91049b9ab4  562.0  152.0  256.0   453.0       1
2  00704310-78a8-4b38-8475-49f4573b2dbb  323.0  577.0  160.0   104.0       1
3  00704310-78a8-4b38-8475-49f4573b2dbb  695.0  575.0  162.0   137.0       1
4  00aecb01-a116-45a2-956c-08d2fa55433f  288.0  322.0   94.0   135.0       1

In [18]:
downsamplde_data = balanced_df.sample(frac=0.001, ignore_index=True)
downsamplde_data.sort_values(by="patientId", inplace=True)
downsamplde_data.shape
downsamplde_data.head()

                               patientId      x      y  width  height  Target
2   0f87bb25-447f-4c72-b91c-f85824435051    NaN    NaN    NaN     NaN       0
10  2bf8a7ed-b4a5-4ea1-b8e8-cadc7f7adf2d  179.0  254.0  253.0   523.0       1
4   2e4b20f7-69c4-4680-9c8b-6984c195b1cf  176.0  595.0  124.0   117.0       1
12  3ecaaa65-d48a-4b92-8b65-cd37c32da231  231.0  669.0  188.0   134.0       1
7   477b167a-6a23-4fa4-bdd7-ed33c6ea7daa  565.0  436.0  284.0   352.0       1

In [19]:
downsamplde_data.to_csv("downsampled_data.csv", index=False)

In [8]:
print((balanced_df["Target"] == 0).sum())
print((balanced_df["Target"] == 1).sum())

9555
9555

In [9]:
balanced_df.to_csv("resampled_data.csv", index=False)

In [10]:
d = pd.read_csv("resampled_data.csv")
d.shape[0]/2

9555.0

In [11]:
d["patientId"].duplicated().sum()

np.int64(3543)